import { PropertyCardProps } from "../utils/types";

const propiedades: PropertyCardProps[] = [
  {
    id: 1,
    title: "Propiedad A",
    imageSrc: ["https://placehold.co/300x300"],
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
    status: "en venta",
    price: "U$S 100.000",
    type: "apartamento",
  },
  {
    id: 2,
    title: "Propiedad B",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum lorem ipsum dolor sit amet consectetur adipisicing elit.",
    status: "en alquiler",
    price: "U$S 80.000",
    type: "apartamento",
  },
  {
    id: 3,
    title: "Propiedad C",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit amet consectetur adipisicing elitlorem ipsur adipisicing elit",
    status: "en venta",
    price: "U$S 120.000",
    type: "apartamento",
  },
  {
    id: 4,
    title: "Propiedad D",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit lorem ipsum dolor sit amet consectetur adipisicing elit",
    status: "reservada",
    price: "U$S 90.000",
    type: "apartamento",
  },
  {
    id: 5,
    title: "Propiedad E",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit amet consectetur lorem ipsum dolor stur adipisicing elit",
    status: "en venta",
    price: "U$S 110.000",
    type: "apartamento",
  },
  {
    id: 6,
    title: "Propiedad F",
    imageSrc: ["https://placehold.co/300x300"],
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
    status: "en venta",
    price: "U$S 95.000",
    type: "apartamento",
  },
  {
    id: 7,
    title: "Propiedad G",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum lorem ipsum dolor sit amet consectetur adipisicing elit.",
    status: "en alquiler",
    price: "U$S 75.000",
    type: "apartamento",
  },
  {
    id: 8,
    title: "Propiedad H",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit amet consectetur adipisicit amet consectetur adipisicing elit",
    status: "en venta",
    price: "U$S 130.000",
    type: "apartamento",
  },
  {
    id: 9,
    title: "Propiedad I",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit lorem ipsum dolor sit amet consectetur adipisicing elit",
    status: "reservada",
    price: "U$S 85.000",
    type: "apartamento",
  },
  {
    id: 10,
    title: "Propiedad J",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit amet consectetur lorem ipsum ctetur adipisicing elit",
    status: "en venta",
    price: "U$S 125.000",
    type: "apartamento",
  },
  {
    id: 11,
    title: "Propiedad K",
    imageSrc: ["https://placehold.co/300x300"],
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
    status: "en venta",
    price: "U$S 105.000",
    type: "apartamento",
  },
  {
    id: 12,
    title: "Propiedad L",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum lorem ipsum dolor sit amet consectetur adipisicing elit.",
    status: "en alquiler",
    price: "U$S 90.000",
    type: "terreno",
  },
  {
    id: 13,
    title: "Propiedad M",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit amet consectetur adipisicing sectetur adipisicing elit",
    status: "en venta",
    price: "U$S 140.000",
    type: "terreno",
  },
  {
    id: 14,
    title: "Propiedad N",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit lorem ipsum dolor sit amet consectetur adipisicing elit",
    status: "reservada",
    price: "U$S 100.000",
    type: "terreno",
  },
  {
    id: 15,
    title: "Propiedad O",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit amet consectetur lorem ipsum doloipisicing elit",
    status: "en venta",
    price: "U$S 135.000",
    type: "casa",
  },
  {
    id: 16,
    title: "Propiedad P",
    imageSrc: ["https://placehold.co/300x300"],
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
    status: "en venta",
    price: "U$S 115.000",
    type: "casa",
  },
  {
    id: 17,
    title: "Propiedad Q",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum lorem ipsum dolor sit amet consectetur adipisicing elit.",
    status: "en alquiler",
    price: "U$S 95.000",
    type: "casa",
  },
  {
    id: 18,
    title: "Propiedad R",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit amet consectetur adipisicing et dipisicing elit",
    status: "en venta",
    price: "U$S 150.000",
    type: "casa",
  },
  {
    id: 19,
    title: "Propiedad S",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit lorem ipsum dolor sit amet consectetur adipisicing elit",
    status: "reservada",
    price: "U$S 105.000",
    type: "casa",
  },
  {
    id: 20,
    title: "Propiedad T",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit amet consectetur lorem ipsum dolor siicing elit",
    status: "en venta",
    price: "U$S 145.000",
    type: "casa",
  },
  {
    id: 21,
    title: "Propiedad U",
    imageSrc: ["https://placehold.co/300x300"],
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit",
    status: "en venta",
    price: "U$S 155.000",
    type: "casa",
  },
  // Propiedades de alquiler adicionales
  {
    id: 22,
    title: "Propiedad V",
    imageSrc: ["https://placehold.co/300x300"],
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
    status: "en alquiler",
    price: "U$S 101.000",
    type: "casa",
  },
  {
    id: 23,
    title: "Propiedad W",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum lorem ipsum dolor sit amet consectetur adipisicing elit.",
    status: "en alquiler",
    price: "U$S 81.000",
    type: "casa",
  },
  {
    id: 24,
    title: "Propiedad X",
    imageSrc: ["https://placehold.co/300x300"],
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
    status: "en alquiler",
    price: "U$S 121.000",
    type: "casa",
  },
  {
    id: 25,
    title: "Propiedad Y",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit lorem ipsum dolor sit amet consectetur adipisicing elit",
    status: "reservada",
    price: "U$S 91.000",
    type: "oficina",
  },
  {
    id: 26,
    title: "Propiedad Z",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit amet consectetur lorem ipsum dolor sit elit",
    status: "en alquiler",
    price: "U$S 111.000",
    type: "oficina",
  },
  {
    id: 27,
    title: "Propiedad AA",
    imageSrc: ["https://placehold.co/300x300"],
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
    status: "en alquiler",
    price: "U$S 96.000",
    type: "comercio",
  },
  {
    id: 28,
    title: "Propiedad AB",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum lorem ipsum dolor sit amet consectetur adipisicing elit.",
    status: "en alquiler",
    price: "U$S 86.000",
    type: "comercio",
  },
  {
    id: 29,
    title: "Propiedad AC",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit amet consectetur adipisicing elitlore  adipisicing elit",
    status: "en alquiler",
    price: "U$S 131.000",
    type: "comercio",
  },
  {
    id: 30,
    title: "Propiedad AD",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit lorem ipsum dolor sit amet consectetur adipisicing elit",
    status: "en alquiler",
    price: "U$S 121.000",
    type: "comercio",
  },
  {
    id: 31,
    title: "Propiedad AE",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit amet consectetur lorem ipsum dolor sit amet consectetur adipisicing elit",
    status: "en alquiler",
    price: "U$S 116.000",
    type: "oficina",
  },
  {
    id: 32,
    title: "Propiedad AF",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum lorem ipsum dolor sit amet consectetur adipisicing elit.",
    status: "en alquiler",
    price: "U$S 106.000",
    type: "oficina",
  },
  {
    id: 33,
    title: "Propiedad AG",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit amet consectetur adipisicing   consectetur adipisicing elit",
    status: "en alquiler",
    price: "U$S 141.000",
    type: "oficina",
  },
  {
    id: 34,
    title: "Propiedad AH",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit lorem ipsum dolor sit amet consectetur adipisicing elit",
    status: "en alquiler",
    price: "U$S 131.000",
    type: "apartamento",
  },
  {
    id: 35,
    title: "Propiedad AI",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum lorem ipsum dolor sit amet consectetur adipisicing elit.",
    status: "en alquiler",
    price: "U$S 121.000",
    type: "apartamento",
  },
  {
    id: 36,
    title: "Propiedad AJ",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit amet consectetur lorem ipsum dolor sit  elit",
    status: "en alquiler",
    price: "U$S 111.000",
    type: "almacen",
  },
  {
    id: 37,
    title: "Propiedad AK",
    imageSrc: ["https://placehold.co/300x300"],
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
    status: "en alquiler",
    price: "U$S 101.000",
    type: "almacen",
  },
  {
    id: 38,
    title: "Propiedad AL",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum lorem ipsum dolor sit amet consectetur adipisicing elit.",
    status: "en alquiler",
    price: "U$S 96.000",
    type: "almacen",
  },
  {
    id: 39,
    title: "Propiedad AM",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit amet consectetur adipisicing elitlorem ip consectetur adipisicing elit",
    status: "en alquiler",
    price: "U$S 91.000",
    type: "almacen",
  },
  {
    id: 40,
    title: "Propiedad AN",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit lorem ipsum dolor sit amet consectetur adipisicing elit",
    status: "en alquiler",
    price: "U$S 86.000",
    type: "almacen",
  },
  {
    id: 41,
    title: "Propiedad AO",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit amet consectetur lorem ipsum dolor sit amet ß adipisicing elit",
    status: "en alquiler",
    price: "U$S 81.000",
    type: "casa",
  },
  {
    id: 42,
    title: "Propiedad AP",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit amet consectetur lorem ipsum dolor sit amet ß adipisicing elit",
    status: "en alquiler",
    price: "U$S 800.000",
    type: "casa",
  },
  // Propiedades de venta adicionales
  {
    id: 43,
    title: "Propiedad AQ",
    imageSrc: ["https://placehold.co/300x300"],
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
    status: "en venta",
    price: "U$S 102.000",
    type: "casa",
  },
  {
    id: 44,
    title: "Propiedad AR",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum lorem ipsum dolor sit amet consectetur adipisicing elit.",
    status: "en venta",
    price: "U$S 82.000",
    type: "casa",
  },
  {
    id: 45,
    title: "Propiedad AS",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit amet consectetur adipisicing elitlorem ipsum  ",
    status: "en venta",
    price: "U$S 122.000",
    type: "casa",
  },
  {
    id: 46,
    title: "Propiedad AT",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit lorem ipsum dolor sit amet consectetur adipisicing elit",
    status: "reservada",
    price: "U$S 92.000",
    type: "casa",
  },
  {
    id: 47,
    title: "Propiedad AU",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit amet consectetur lorem ipsum dolor sit a ",
    status: "en venta",
    price: "U$S 112.000",
    type: "casa",
  },
  {
    id: 48,
    title: "Propiedad AV",
    imageSrc: ["https://placehold.co/300x300"],
    description: "lorem ipsum dolor sit amet consectetur adipisicing elit.",
    status: "en venta",
    price: "U$S 97.000",
    type: "casa",
  },
  {
    id: 49,
    title: "Propiedad AW",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum lorem ipsum dolor sit amet consectetur adipisicing elit.",
    status: "en venta",
    price: "U$S 87.000",
    type: "casa",
  },
  {
    id: 50,
    title: "Propiedad AX",
    imageSrc: ["https://placehold.co/300x300"],
    description: "lorem ipsum dolor sit amet consectetur  adipisicing elit",
    status: "en venta",
    price: "U$S 132.000",
    type: "casa",
  },
  {
    id: 51,
    title: "Propiedad AY",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit lorem ipsum dolor sit amet consectetur adipisicing elit",
    status: "en venta",
    price: "U$S 122.000",
    type: "casa",
  },
  {
    id: 52,
    title: "Propiedad AZ",
    imageSrc: ["https://placehold.co/300x300"],
    description:
      "lorem ipsum dolor sit amet consectetur lorem ipsum dolor sit   adipisicing elit",
    status: "en venta",
    price: "U$S 117.000",
    type: "terreno",
  },
];

export default propiedades;

